version: '3'
services:
  ttt_discord: 
    image: ghcr.io/jdenda/discord_gmod_bot:latest
    user: node
    volumes:
      - ./config/.env:/home/node/discord_gmod_bot/.env
    ports:
      - 81:443
      - 37405:37405